export enum InfluencerOrderBy {
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  ONBOARDED_AT_ASC = 'ONBOARDED_AT_ASC',
  ONBOARDED_AT_DESC = 'ONBOARDED_AT_DESC',
  TOTALRAISEDAMOUNT_ASC = 'TOTALRAISEDAMOUNT_ASC',
  TOTALRAISEDAMOUNT_DESC = 'TOTALRAISEDAMOUNT_DESC',
}
