export enum CharityOrderBy {
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  ACTIVATED_AT_ASC = 'ACTIVATED_AT_ASC',
  ACTIVATED_AT_DESC = 'ACTIVATED_AT_DESC',
  TOTALRAISEDAMOUNT_ASC = 'TOTALRAISEDAMOUNT_ASC',
  TOTALRAISEDAMOUNT_DESC = 'TOTALRAISEDAMOUNT_DESC',
}
