name: build-pull-request

on:
  pull_request:
    branches: [ main ]

env:
  SERVICE_NAME: contrib-app

  ENV_REACT_APP_AUTH0_DOMAIN: "auth.contrib.org"
  ENV_REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.DEV_AUTH0_CLIENT_ID }}
  ENV_REACT_APP_PLATFORM_URL: "https://dev.contrib.org/"
  ENV_REACT_APP_API_URL: "https://dev.contrib.org/graphql"
  ENV_REACT_APP_API_AUDIENCE: "https://dev.contrib.org/"

jobs:
  setup-build-deploy:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Node
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    # Build Client
    - name: Build Client
      run: REACT_APP_AUTH0_DOMAIN=$ENV_REACT_APP_AUTH0_DOMAIN REACT_APP_AUTH0_CLIENT_ID=$ENV_REACT_APP_AUTH0_CLIENT_ID REACT_APP_PLATFORM_URL=$ENV_REACT_APP_PLATFORM_URL REACT_APP_API_URL=$ENV_REACT_APP_API_URL REACT_APP_API_AUDIENCE=$ENV_REACT_APP_API_AUDIENCE yarn build-client

    # Test Client
    - name: Test Client
      run: yarn test-client

    # Build Server
    - name: Build Server
      run: yarn build-server

    # Test Server
    - name: Test Server and Coverage
      run: yarn test-server     
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.15
      with:
        token: ${{ secrets.CODECOV_KEY }}  



