name: deploy-to-live

on:
  release:
    types: [released]

env:
  PROJECT_ID: ${{ secrets.LIVE_GCP_PROJECT_ID }}
  SERVICE_NAME: contrib-app

  #Server Env
  ENV_NEW_RELIC_APP_NAME: contrib-app-live
  ENV_NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  ENV_MONGODB_URI: ${{ secrets.LIVE_MONGODB_URI }}
  ENV_AUTH0_ISSUER_URL: https://auth.contrib.org
  ENV_AUTH0_AUDIENCE: http://live.contrib.org
  ENV_AUTH0_MANAGEMENT_DOMAIN: contrib.us.auth0.com
  ENV_AUTH0_MANAGEMENT_CLIENT_ID: dj4DaWeggmOb7cbCOSxzSQAN5EYBwVqr
  ENV_AUTH0_MANAGEMENT_CLIENT_SECRET: ${{ secrets.LIVE_AUTH0_MANAGEMENT_CLIENT_SECRET }}
  ENV_TWILIO_ACCOUNT_SID: ACd64357f20d26725ac0b45616048e8d84
  ENV_TWILIO_AUTH_TOKEN: ${{ secrets.LIVE_TWILIO_AUTH_TOKEN }}
  ENV_TWILIO_VERIFICATION_SERVICE_SID: ${{ secrets.LIVE_TWILIO_VERIFICATION_SERVICE_SID }}
  ENV_APP_URL: "https://live.contrib.org/"
  ENV_TWILIO_SENDER_NUMBER: +17726178791
  ENV_CONTENT_STORAGE_NAME: content-live.contrib.org
  ENV_CONTENT_STORAGE_KEY: ${{ secrets.LIVE_CONTENT_STORAGE_KEY }}

  # Client Env
  ENV_REACT_APP_AUTH0_DOMAIN: "auth.contrib.org"
  ENV_REACT_APP_AUTH0_CLIENT_ID: dj4DaWeggmOb7cbCOSxzSQAN5EYBwVqr
  ENV_REACT_APP_PLATFORM_URL: "https://live.contrib.org/"
  ENV_REACT_APP_API_URL: "https://live.contrib.org/graphql"
  ENV_REACT_APP_API_AUDIENCE: "https://live.contrib.org/"


jobs:
  setup-build-deploy:
    name: Build and Deploy to Live
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Node
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    # Build Client
    - name: Build Client
      run: REACT_APP_AUTH0_DOMAIN=$ENV_REACT_APP_AUTH0_DOMAIN REACT_APP_AUTH0_CLIENT_ID=$ENV_REACT_APP_AUTH0_CLIENT_ID REACT_APP_PLATFORM_URL=$ENV_REACT_APP_PLATFORM_URL REACT_APP_API_URL=$ENV_REACT_APP_API_URL REACT_APP_API_AUDIENCE=$ENV_REACT_APP_API_AUDIENCE yarn build-client

    # Test Client
    - name: Test Client
      run: yarn test-client

    # Build Server
    - name: Build Server
      run: yarn build-server

    # Test Server
    - name: Test Server and Coverage
      run: yarn test-server     

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.LIVE_GCP_SA_KEY }}
        project_id: ${{ secrets.LIVE_GCP_PROJECT_ID }}
        export_default_credentials: true

    # Build and push image to Google Container Registry
    - name: Docker Auth
      run: gcloud auth configure-docker

    - name: Build Docker Image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

    - name: Docker Push to Google Cloud
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
    
    
    # Deploy image to Cloud Run
    - name: Deploy to [us-west1]
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --cpu=1 --memory=1Gi \
          --platform=managed \
          --region=us-west1 \
          --allow-unauthenticated \
          --port=3000 \
          --set-env-vars=NEW_RELIC_APP_NAME=$ENV_NEW_RELIC_APP_NAME \
          --set-env-vars=NEW_RELIC_LICENSE_KEY=$ENV_NEW_RELIC_LICENSE_KEY \
          --set-env-vars=MONGODB_URI=$ENV_MONGODB_URI \
          --set-env-vars=APP_URL=$ENV_APP_URL \
          --set-env-vars=TWILIO_ACCOUNT_SID=$ENV_TWILIO_ACCOUNT_SID \
          --set-env-vars=TWILIO_AUTH_TOKEN=$ENV_TWILIO_AUTH_TOKEN \
          --set-env-vars=TWILIO_VERIFICATION_SERVICE_SID=$ENV_TWILIO_VERIFICATION_SERVICE_SID \
          --set-env-vars=TWILIO_SENDER_NUMBER=$ENV_TWILIO_SENDER_NUMBER \
          --set-env-vars=AUTH0_ISSUER_URL=$ENV_AUTH0_ISSUER_URL \
          --set-env-vars=AUTH0_AUDIENCE=$ENV_AUTH0_AUDIENCE \
          --set-env-vars=AUTH0_MANAGEMENT_DOMAIN=$ENV_AUTH0_MANAGEMENT_DOMAIN \
          --set-env-vars=AUTH0_MANAGEMENT_CLIENT_ID=$ENV_AUTH0_MANAGEMENT_CLIENT_ID \
          --set-env-vars=AUTH0_MANAGEMENT_CLIENT_SECRET=$ENV_AUTH0_MANAGEMENT_CLIENT_SECRET
          --set-env-vars=CONTENT_STORAGE_NAME=$ENV_CONTENT_STORAGE_NAME \
          --set-env-vars=CONTENT_STORAGE_KEY=$ENV_CONTENT_STORAGE_KEY

    - name: Deploy to [us-central1]
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --cpu=1 --memory=1Gi \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --port=3000 \
          --set-env-vars=NEW_RELIC_APP_NAME=$ENV_NEW_RELIC_APP_NAME \
          --set-env-vars=NEW_RELIC_LICENSE_KEY=$ENV_NEW_RELIC_LICENSE_KEY \
          --set-env-vars=MONGODB_URI=$ENV_MONGODB_URI \
          --set-env-vars=APP_URL=$ENV_APP_URL \
          --set-env-vars=TWILIO_ACCOUNT_SID=$ENV_TWILIO_ACCOUNT_SID \
          --set-env-vars=TWILIO_AUTH_TOKEN=$ENV_TWILIO_AUTH_TOKEN \
          --set-env-vars=TWILIO_VERIFICATION_SERVICE_SID=$ENV_TWILIO_VERIFICATION_SERVICE_SID \
          --set-env-vars=TWILIO_SENDER_NUMBER=$ENV_TWILIO_SENDER_NUMBER \
          --set-env-vars=AUTH0_ISSUER_URL=$ENV_AUTH0_ISSUER_URL \
          --set-env-vars=AUTH0_AUDIENCE=$ENV_AUTH0_AUDIENCE \
          --set-env-vars=AUTH0_MANAGEMENT_DOMAIN=$ENV_AUTH0_MANAGEMENT_DOMAIN \
          --set-env-vars=AUTH0_MANAGEMENT_CLIENT_ID=$ENV_AUTH0_MANAGEMENT_CLIENT_ID \
          --set-env-vars=AUTH0_MANAGEMENT_CLIENT_SECRET=$ENV_AUTH0_MANAGEMENT_CLIENT_SECRET
          --set-env-vars=CONTENT_STORAGE_NAME=$ENV_CONTENT_STORAGE_NAME \
          --set-env-vars=CONTENT_STORAGE_KEY=$ENV_CONTENT_STORAGE_KEY
