name: deploy-to-dev

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.DEV_GCP_PROJECT_ID }}
  SERVICE_NAME: contrib-app

  #Server Env
  ENV_NEW_RELIC_APP_NAME: contrib-app-dev
  ENV_NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  ENV_MONGODB_URI: ${{ secrets.DEV_MONGODB_URI }}
  ENV_AUTH0_ISSUER_URL: https://contrib.us.auth0.com/
  ENV_AUTH0_AUDIENCE: https://dev.contrib.org
  ENV_AUTH0_MANAGEMENT_DOMAIN: contrib.us.auth0.com
  ENV_AUTH0_MANAGEMENT_CLIENT_ID: dj4DaWeggmOb7cbCOSxzSQAN5EYBwVqr
  ENV_AUTH0_MANAGEMENT_CLIENT_SECRET: ${{ secrets.DEV_AUTH0_MANAGEMENT_CLIENT_SECRET }}
  ENV_TWILIO_ACCOUNT_SID: ACd64357f20d26725ac0b45616048e8d84
  ENV_TWILIO_AUTH_TOKEN: ${{ secrets.DEV_TWILIO_AUTH_TOKEN }}
  ENV_TWILIO_VERIFICATION_SERVICE_SID: ${{ secrets.DEV_TWILIO_VERIFICATION_SERVICE_SID }}
  ENV_APP_URL: "https://dev.contrib.org/"
  ENV_TWILIO_SENDER_NUMBER: +17726178791
  ENV_CONTENT_STORAGE_NAME: content-dev.contrib.org
  ENV_CONTENT_STORAGE_KEY: ${{ secrets.DEV_CONTENT_STORAGE_KEY }}
  ENV_AUCTION_SCHEDULER_SECRET: secret_key_for_auctions_scheduler
  ENV_CLOUDFLARE_STREAMING_KEY: ${{ secrets.DEV_CLOUDFLARE_STREAMING_KEY }}
  ENV_CLOUDFLARE_USER_ID: ${{ secrets.DEV_CLOUDFLARE_USER_ID }}
  ENV_BITLY_DOMAIN: go.contrib.org
  ENV_BITLY_ACCESS_TOKEN: ${{ secrets.DEV_BITLY_ACCESS_TOKEN }}
  ENV_STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
  ENV_STRIPE_WEBHOOK_SECRET_KEY: ${{ secrets.DEV_STRIPE_WEBHOOK_SECRET_KEY }}
  ENV_FACEBOOK_APP_ID: 247741353494875

jobs:
  setup-build-deploy:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build Client
      - name: Build Client
        run: yarn build-client
        env:
          REACT_APP_AUTH0_DOMAIN: "contrib.us.auth0.com"
          REACT_APP_AUTH0_CLIENT_ID: 2ySlxFOLW1Rw1ALES7cF3tH9Hz6zDO57
          REACT_APP_PLATFORM_URL: "https://dev.contrib.org/"
          REACT_APP_API_URL: "https://dev.contrib.org/graphql"
          REACT_APP_API_AUDIENCE: "https://dev.contrib.org"
          REACT_APP_USE_NEWRELIC: true
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.DEV_REACT_APP_STRIPE_PUBLISHABLE_KEY }}
          REACT_APP_INTERCOM_APP_ID: ${{ secrets.DEV_REACT_APP_INTERCOM_APP_ID }}
          REACT_APP_FULLSTORY_ORG_ID: ${{ secrets.DEV_REACT_APP_FULLSTORY_ORG_ID }}
          REACT_APP_MAX_SIZE_VIDEO_GB: "1"

      # Test Client
      - name: Test Client
        run: yarn test-client

      # Build Server
      - name: Build Server
        run: yarn build-server

      # Test Server
      - name: Test Server
        run: yarn test-server

      - name: Code Coverage
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_KEY }}

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          export_default_credentials: true

      # Build and push image to Google Container Registry
      - name: Docker Auth
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Docker Push to Google Cloud
        run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy
        run: >-
          gcloud run deploy $SERVICE_NAME
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          --cpu=1 --memory=1Gi
          --platform=managed
          --region=us-central1
          --allow-unauthenticated
          --port=3000
          --set-env-vars="^ ___^NEW_RELIC_APP_NAME=$ENV_NEW_RELIC_APP_NAME
          ___NEW_RELIC_LICENSE_KEY=$ENV_NEW_RELIC_LICENSE_KEY
          ___NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
          ___MONGODB_URI=$ENV_MONGODB_URI
          ___APP_URL=$ENV_APP_URL
          ___TWILIO_ACCOUNT_SID=$ENV_TWILIO_ACCOUNT_SID
          ___TWILIO_AUTH_TOKEN=$ENV_TWILIO_AUTH_TOKEN
          ___TWILIO_VERIFICATION_SERVICE_SID=$ENV_TWILIO_VERIFICATION_SERVICE_SID
          ___TWILIO_SENDER_NUMBER=$ENV_TWILIO_SENDER_NUMBER
          ___AUTH0_ISSUER_URL=$ENV_AUTH0_ISSUER_URL
          ___AUTH0_AUDIENCE=$ENV_AUTH0_AUDIENCE
          ___AUTH0_MANAGEMENT_DOMAIN=$ENV_AUTH0_MANAGEMENT_DOMAIN
          ___AUTH0_MANAGEMENT_CLIENT_ID=$ENV_AUTH0_MANAGEMENT_CLIENT_ID
          ___AUTH0_MANAGEMENT_CLIENT_SECRET=$ENV_AUTH0_MANAGEMENT_CLIENT_SECRET
          ___CONTENT_STORAGE_NAME=$ENV_CONTENT_STORAGE_NAME
          ___CONTENT_STORAGE_KEY=$ENV_CONTENT_STORAGE_KEY
          ___AUCTION_SCHEDULER_SECRET=$ENV_AUCTION_SCHEDULER_SECRET
          ___CLOUDFLARE_STREAMING_KEY=$ENV_CLOUDFLARE_STREAMING_KEY
          ___CLOUDFLARE_USER_ID=$ENV_CLOUDFLARE_USER_ID
          ___BITLY_ACCESS_TOKEN=$ENV_BITLY_ACCESS_TOKEN
          ___STRIPE_SECRET_KEY=$ENV_STRIPE_SECRET_KEY
          ___STRIPE_WEBHOOK_SECRET_KEY=$ENV_STRIPE_WEBHOOK_SECRET_KEY
          ___BITLY_DOMAIN=$ENV_BITLY_DOMAIN
          ___FACEBOOK_APP_ID=$ENV_FACEBOOK_APP_ID"
