# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy to Dev

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.DEV_GCP_PROJECT_ID }}
  SERVICE_NAME: contrib-app
  NEW_RELIC_APP_NAME: contrib-app-dev
  NEWRELIC_LICENSE_KEY: ${{ secrets.NEWRELIC_LICENSE_KEY }}
  MONGODB_URI: ${{ secrets.DEV_MONGODB_URI }}
  GOOGLE_CLIENT_ID: ${{ secrets.DEV_GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.DEV_GOOGLE_CLIENT_SECRET }}
  FB_CLIENT_ID: ${{ secrets.DEV_FB_CLIENT_ID }}
  FB_CLIENT_SECRET: ${{ secrets.DEV_FB_CLIENT_SECRET }}
  TWITTER_CLIENT_ID: ${{ secrets.DEV_TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.DEV_TWITTER_CLIENT_SECRET }}
  SESSION_SECRET: ${{ secrets.DEV_SESSION_SECRET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build Client
    - name: Build Client
      run: yarn build-client

    # Test Client
    - name: Test Client
      run: yarn test-client

    # Build Server
    - name: Build Server
      run: yarn build-server

    # Test Server
    - name: Test Server and Coverage
      run: yarn test-server     
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.15
      with:
        token: ${{ secrets.CODECOV_KEY }}  

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
        project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
        export_default_credentials: true

    # Build and push image to Google Container Registry
    - name: Docker Auth
      run: gcloud auth configure-docker

    - name: Build Docker Image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

    - name: Docker Push to Google Cloud
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
    
    
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --cpu=1 --memory=1Gi \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --set-env-vars=MONGODB_URI=$MONGODB_URI,GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET,FB_CLIENT_ID=$FB_CLIENT_ID,FB_CLIENT_SECRET=$FB_CLIENT_SECRET,TWITTER_CLIENT_ID=$TWITTER_CLIENT_ID,TWITTER_CLIENT_SECRET=$TWITTER_CLIENT_SECRET,SESSION_SECRET=$SESSION_SECRET \
          --port=3000
