name: deploy-to-live

on:
  release:
    types: [released]

env:
  PROJECT_ID: ${{ secrets.LIVE_GCP_PROJECT_ID }}
  SERVICE_NAME: contrib-app

  #Server Env
  ENV_NEW_RELIC_APP_NAME: contrib-app-live
  ENV_NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  ENV_MONGODB_URI: ${{ secrets.LIVE_MONGODB_URI }}
  ENV_TWILIO_ACCOUNT_SID: ACd64357f20d26725ac0b45616048e8d84
  ENV_TWILIO_AUTH_TOKEN: ${{ secrets.LIVE_TWILIO_AUTH_TOKEN }}
  ENV_TWILIO_VERIFICATION_SERVICE_SID: ${{ secrets.LIVE_TWILIO_VERIFICATION_SERVICE_SID }}
  ENV_APP_URL: "https://contrib.org/"
  ENV_AUTH_API_URL: https://contrib.org/
  ENV_GOOGLE_CLIENT_ID: ${{ secrets.LIVE_GOOGLE_CLIENT_ID }}
  ENV_GOOGLE_CLIENT_SECRET: ${{ secrets.LIVE_GOOGLE_CLIENT_SECRET }}
  ENV_FACEBOOK_APP_ID: ${{ secrets.LIVE_FACEBOOK_APP_ID }}
  ENV_FACEBOOK_APP_SECRET: ${{ secrets.LIVE_FACEBOOK_APP_SECRET }}
  ENV_TWITTER_CONSUMER_KEY: ${{ secrets.LIVE_TWITTER_CONSUMER_KEY }}
  ENV_TWITTER_CONSUMER_SECRET: ${{ secrets.LIVE_TWITTER_CONSUMER_SECRET }}
  ENV_COOKIE_KEY_SECRET: ${{ secrets.LIVE_COOKIE_KEY_SECRET }}
  ENV_COOKIE_LIFE_TIME_MINS: 7243
  ENV_TWILIO_SENDER_NUMBER: +17726178791
  ENV_CONTENT_STORAGE_NAME: content-live.contrib.org
  ENV_CONTENT_STORAGE_KEY: ${{ secrets.LIVE_CONTENT_STORAGE_KEY }}
  ENV_UPS_DELIVERY_REQUEST_HEADER: ${{ secrets.LIVE_UPS_DELIVERY_REQUEST_HEADER }}
  ENV_UPS_DELIVERY_CONTRIB_DATA: ${{ secrets.LIVE_UPS_DELIVERY_CONTRIB_DATA }}
  ENV_UPS_TEST_ENVIROMENT: false
  ENV_UPS_SMS_WITH_DELIVERY_LINK: true
  ENV_UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS: ${{ secrets.LIVE_UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS }}
  ENV_AUCTION_SCHEDULER_SECRET: ${{ secrets.LIVE_AUCTION_SCHEDULER_SECRET }}
  ENV_CLOUDFLARE_STREAMING_KEY: ${{ secrets.LIVE_CLOUDFLARE_STREAMING_KEY }}
  ENV_CLOUDFLARE_USER_ID: ${{ secrets.LIVE_CLOUDFLARE_USER_ID }}
  ENV_STRIPE_SECRET_KEY: ${{ secrets.LIVE_STRIPE_SECRET_KEY }}
  ENV_STRIPE_WEBHOOK_SECRET_KEY: ${{ secrets.LIVE_STRIPE_WEBHOOK_SECRET_KEY }}
  ENV_STRIPE_CONTRIB_SHARE_PERCENTAGE: ${{ secrets.LIVE_STRIPE_CONTRIB_SHARE_PERCENTAGE }}
  ENV_FACEBOOK_APP_ID: 247741353494875
  ENV_MAX_SIZE_VIDEO_GB: 0.2
  ENV_GOOGLE_CLOUD_PROJECT: contrib-live
  ENV_GOOGLE_CLOUD_LOCATION: us-central1
  ENV_GOOGLE_CLOUD_TASK_QUEUE: bids-notification
  ENV_GOOGLE_CLOUD_TASK_API_TOKEN: ${{ secrets.LIVE_GOOGLE_CLOUD_TASK_API_TOKEN }}
  ENV_NOTIFICATION_TASK_TARGET_URL: api/v1/notification

jobs:
  setup-build-deploy:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build Client
      - name: Build Client
        run: yarn build-client
        env:
          REACT_APP_PLATFORM_URL: "https://contrib.org/"
          REACT_APP_API_URL: "https://contrib.org/graphql"
          REACT_APP_API_AUDIENCE: "https://contrib.org"
          REACT_APP_USE_NEWRELIC: true
          REACT_APP_NEWRELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          REACT_APP_NEWRELIC_APPLICATION_ID: "916719636"
          REACT_APP_NEWRELIC_ACCOUNT_ID: "2921752"
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.LIVE_REACT_APP_STRIPE_PUBLISHABLE_KEY }}
          REACT_APP_INTERCOM_APP_ID: ${{ secrets.LIVE_REACT_APP_INTERCOM_APP_ID }}
          REACT_APP_FULLSTORY_ORG_ID: ${{ secrets.LIVE_REACT_APP_FULLSTORY_ORG_ID }}
          REACT_APP_MAX_SIZE_VIDEO_GB: 0.2
          REACT_APP_GOOGLE_ANALYTICS_APP_ID: "G-T3VD43X4L3"
          REACT_APP_SMARTLOOK_ID: ${{ secrets.LIVE_REACT_APP_SMARTLOOK_ID }}
          REACT_APP_UPS_SHOW_LINK_ON_THE_AUCTION_PAGE: true

      # Test Client
      - name: Test Client
        run: yarn test-client

      # Build Server
      - name: Build Server
        run: yarn build-server

      # Test Server
      - name: Test Server
        run: yarn test-server

      - name: Code Coverage
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_KEY }}

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.LIVE_GCP_SA_KEY }}
          project_id: ${{ secrets.LIVE_GCP_PROJECT_ID }}
          export_default_credentials: true

      # Build and push image to Google Container Registry
      - name: Docker Auth
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Docker Push to Google Cloud
        run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy to US-Central1
        run: >-
          gcloud run deploy $SERVICE_NAME
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          --cpu=1
          --memory=1Gi
          --platform=managed
          --region=us-central1
          --allow-unauthenticated
          --port=3000
          --set-env-vars="^ ___^NEW_RELIC_APP_NAME=$ENV_NEW_RELIC_APP_NAME
          ___NEW_RELIC_LICENSE_KEY=$ENV_NEW_RELIC_LICENSE_KEY
          ___MONGODB_URI=$ENV_MONGODB_URI
          ___APP_URL=$ENV_APP_URL
          ___AUTH_API_URL=$ENV_AUTH_API_URL
          ___GOOGLE_CLIENT_ID=$ENV_GOOGLE_CLIENT_ID
          ___GOOGLE_CLIENT_SECRET=$ENV_GOOGLE_CLIENT_SECRET
          ___FACEBOOK_APP_ID=$ENV_FACEBOOK_APP_ID
          ___FACEBOOK_APP_SECRET=$ENV_FACEBOOK_APP_SECRET
          ___TWITTER_CONSUMER_KEY=$ENV_TWITTER_CONSUMER_KEY
          ___TWITTER_CONSUMER_SECRET=$ENV_TWITTER_CONSUMER_SECRET
          ___COOKIE_KEY_SECRET=$ENV_COOKIE_KEY_SECRET
          ___COOKIE_LIFE_TIME_MINS=$ENV_COOKIE_LIFE_TIME_MINS
          ___TWILIO_ACCOUNT_SID=$ENV_TWILIO_ACCOUNT_SID
          ___TWILIO_AUTH_TOKEN=$ENV_TWILIO_AUTH_TOKEN
          ___TWILIO_VERIFICATION_SERVICE_SID=$ENV_TWILIO_VERIFICATION_SERVICE_SID
          ___TWILIO_SENDER_NUMBER=$ENV_TWILIO_SENDER_NUMBER
          ___CONTENT_STORAGE_NAME=$ENV_CONTENT_STORAGE_NAME
          ___CONTENT_STORAGE_KEY=$ENV_CONTENT_STORAGE_KEY
          ___UPS_DELIVERY_CONTRIB_DATA=$ENV_UPS_DELIVERY_CONTRIB_DATA
          ___UPS_TEST_ENVIROMENT=$ENV_UPS_TEST_ENVIROMENT
          ___UPS_SMS_WITH_DELIVERY_LINK=$ENV_UPS_SMS_WITH_DELIVERY_LINK
          ___UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS=$ENV_UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS
          ___UPS_DELIVERY_REQUEST_HEADER=$ENV_UPS_DELIVERY_REQUEST_HEADER
          ___AUCTION_SCHEDULER_SECRET=$ENV_AUCTION_SCHEDULER_SECRET
          ___CLOUDFLARE_STREAMING_KEY=$ENV_CLOUDFLARE_STREAMING_KEY
          ___CLOUDFLARE_USER_ID=$ENV_CLOUDFLARE_USER_ID
          ___STRIPE_SECRET_KEY=$ENV_STRIPE_SECRET_KEY
          ___STRIPE_WEBHOOK_SECRET_KEY=$ENV_STRIPE_WEBHOOK_SECRET_KEY
          ___STRIPE_CONTRIB_SHARE_PERCENTAGE=$ENV_STRIPE_CONTRIB_SHARE_PERCENTAGE
          ___FACEBOOK_APP_ID=$ENV_FACEBOOK_APP_ID
          ___MAX_SIZE_VIDEO_GB=$ENV_MAX_SIZE_VIDEO_GB
          ___GOOGLE_CLOUD_PROJECT=$ENV_GOOGLE_CLOUD_PROJECT
          ___GOOGLE_CLOUD_LOCATION=$ENV_GOOGLE_CLOUD_LOCATION
          ___GOOGLE_CLOUD_TASK_QUEUE=$ENV_GOOGLE_CLOUD_TASK_QUEUE
          ___GOOGLE_CLOUD_TASK_API_TOKEN=$ENV_GOOGLE_CLOUD_TASK_API_TOKEN
          ___NOTIFICATION_TASK_TARGET_URL=$ENV_NOTIFICATION_TASK_TARGET_URL"

      - name: Deploy to US-West1
        run: >-
          gcloud run deploy $SERVICE_NAME
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          --cpu=1
          --memory=1Gi
          --platform=managed
          --region=us-west1
          --allow-unauthenticated
          --port=3000
          --set-env-vars="^ ___^NEW_RELIC_APP_NAME=$ENV_NEW_RELIC_APP_NAME
          ___NEW_RELIC_LICENSE_KEY=$ENV_NEW_RELIC_LICENSE_KEY
          ___NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
          ___MONGODB_URI=$ENV_MONGODB_URI
          ___APP_URL=$ENV_APP_URL
          ___AUTH_API_URL=$ENV_AUTH_API_URL
          ___GOOGLE_CLIENT_ID=$ENV_GOOGLE_CLIENT_ID
          ___GOOGLE_CLIENT_SECRET=$ENV_GOOGLE_CLIENT_SECRET
          ___FACEBOOK_APP_ID=$ENV_FACEBOOK_APP_ID
          ___FACEBOOK_APP_SECRET=$ENV_FACEBOOK_APP_SECRET
          ___TWITTER_CONSUMER_KEY=$ENV_TWITTER_CONSUMER_KEY
          ___TWITTER_CONSUMER_SECRET=$ENV_TWITTER_CONSUMER_SECRET
          ___COOKIE_KEY_SECRET=$ENV_COOKIE_KEY_SECRET
          ___COOKIE_LIFE_TIME_MINS=$ENV_COOKIE_LIFE_TIME_MINS
          ___TWILIO_ACCOUNT_SID=$ENV_TWILIO_ACCOUNT_SID
          ___TWILIO_AUTH_TOKEN=$ENV_TWILIO_AUTH_TOKEN
          ___TWILIO_VERIFICATION_SERVICE_SID=$ENV_TWILIO_VERIFICATION_SERVICE_SID
          ___TWILIO_SENDER_NUMBER=$ENV_TWILIO_SENDER_NUMBER
          ___CONTENT_STORAGE_NAME=$ENV_CONTENT_STORAGE_NAME
          ___CONTENT_STORAGE_KEY=$ENV_CONTENT_STORAGE_KEY
          ___UPS_DELIVERY_CONTRIB_DATA=$ENV_UPS_DELIVERY_CONTRIB_DATA
          ___UPS_TEST_ENVIROMENT=$ENV_UPS_TEST_ENVIROMENT
          ___UPS_SMS_WITH_DELIVERY_LINK=$ENV_UPS_SMS_WITH_DELIVERY_LINK
          ___UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS=$ENV_UPS_AUCTION_DEFAULT_PARCEL_PARAMETERS
          ___UPS_DELIVERY_REQUEST_HEADER=$ENV_UPS_DELIVERY_REQUEST_HEADER
          ___AUCTION_SCHEDULER_SECRET=$ENV_AUCTION_SCHEDULER_SECRET
          ___CLOUDFLARE_STREAMING_KEY=$ENV_CLOUDFLARE_STREAMING_KEY
          ___CLOUDFLARE_USER_ID=$ENV_CLOUDFLARE_USER_ID
          ___STRIPE_SECRET_KEY=$ENV_STRIPE_SECRET_KEY
          ___STRIPE_WEBHOOK_SECRET_KEY=$ENV_STRIPE_WEBHOOK_SECRET_KEY
          ___STRIPE_CONTRIB_SHARE_PERCENTAGE=$ENV_STRIPE_CONTRIB_SHARE_PERCENTAGE
          ___FACEBOOK_APP_ID=$ENV_FACEBOOK_APP_ID
          ___MAX_SIZE_VIDEO_GB=$ENV_MAX_SIZE_VIDEO_GB
          ___GOOGLE_CLOUD_PROJECT=$ENV_GOOGLE_CLOUD_PROJECT
          ___GOOGLE_CLOUD_LOCATION=$ENV_GOOGLE_CLOUD_LOCATION
          ___GOOGLE_CLOUD_TASK_QUEUE=$ENV_GOOGLE_CLOUD_TASK_QUEUE
          ___GOOGLE_CLOUD_TASK_API_TOKEN=$ENV_GOOGLE_CLOUD_TASK_API_TOKEN
          ___NOTIFICATION_TASK_TARGET_URL=$ENV_NOTIFICATION_TASK_TARGET_URL"
